[general]
import = [
        "~/.config/alacritty/theme.toml",
]

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"

[[keyboard.bindings]]
key = "Back"
mods = "Control"
chars = "\u0017"
