
[window]
padding = {x =  5, y = 5}
opacity = 0.8
# decorations = "None"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true

[colors.bright]
black = "#444b6a"
blue = "#7da6ff"
cyan = "#0bd9d7"
green = "#b9f27c"
magenta = "#bb9af7"
red = "#ff7a93"
white = "#acb0d0"
yellow = "#ff9e64"

[cursor]
style = {shape = "Beam", blinking = "On"}
blink_interval = 750

[colors.normal]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#787c99"
yellow = "#e0af68"

[colors.primary]
background = "#11121D"
foreground = "#a9b1d6"


[font]
size = 11
offset = {x = 0, y = 0}

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono Nerd Font"
style = "BoldItalic"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "MediumItalic"

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Medium"

[scrolling]
history = 10000
multiplier = 3

[terminal]
shell = "/usr/bin/zsh"


